#!/bin/bash

set -e
ls -lanR /opt/app-root/lib/python2.7
echo "---> Installing application source ..."
cd /tmp/src
pip install -U pip
echo "---> Installing application ..."
pip install .
# set permissions for any installed artifacts
fix-permissions /opt/app-root
